# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emapapp', '0002_celebr_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebr',
            name='last',
            field=models.CharField(default=True, max_length=10000),
            preserve_default=False,
        ),
    ]
