# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Emapapp', '0003_celebr_last'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celebr',
            name='date',
        ),
    ]
