# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 19:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emapapp', '0010_auto_20171226_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='text',
        ),
        migrations.AddField(
            model_name='messages',
            name='mestype',
            field=models.CharField(default=1, max_length=100000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='celebr',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 26, 22, 16, 45, 404580)),
        ),
    ]
